language: node_js
cache: yarn
sudo: required
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn lint
  - yarn test
notifications:
  email: false
