language: node_js
node_js:
  - "lts/*"
cache: yarn
env:
  global:
    - APPLICATION_NAME: styles
cache:
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - yarn build-storybook
script:
  - yarn lint
  - yarn test
  - yarn compile
  - script/build_release.sh $TRAVIS_TAG
deploy:
# deploy storybook files to s3 when merged to base branch
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: storybook-static
  skip_cleanup: true
  on:
    repo: RockefellerArchiveCenter/${APPLICATION_NAME}
    branch: base
  bucket: rac-styleguide
  region: us-east-1
# deploy directory of new tagged release and updated stylelibrary assets to s3
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dist
  skip_cleanup: true
  on:
    tags: true
  bucket: rac-stylelibrary
  region: us-east-1
notifications:
  email: false
