name: update dependencies
on:

  schedule:
    - cron:  '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: base

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: update
        run: yarn install && yarn upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: base
          branch: dependency-updates
          title: Dependency Updates
          commit-message: Dependency updates
